### 服务启动端口号
server:
  port: 8080
spring:
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/design_pattern?useUnicode=true&characterEncoding=UTF-8
logging:
  level:
    com.hxhnzmb.example.mapper: debug